WCSCoavBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: WCSCoavBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        nbSeat:
            type: integer
    lifecycleCallbacks: {  }

    manyToMany:
        passengers:
            targetEntity: WCSCoavBundle\Entity\User
            mappedBy: reservation

    manyToOne:
        reservation:
            targetEntity: WCSCoavBundle\Entity\Flight
            inversedBy: flights


